#!/usr/bin/env python3
"""Bake tools/art/catgirl.png (line art) into src/catgirl_art.h for the talking face.

The head is cropped, the drawn mouth is erased (face.h animates its own), and
copies of the eye rows are made with the eyes shut (blinking) and wiped
(moods that draw their own eyes). Pixels
are stored as 2-bit ink levels (0 = paper .. 3 = black), four per byte.

    python tools/make_catgirl.py [preview.png]
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools/art/catgirl.png"
OUT = ROOT / "src/catgirl_art.h"

CROP_Y0, CROP_Y1 = 60, 600      # ears' tips to just under the chin (source px)
FACE_H = 212                    # screen rows for the art (captions go below)
MOUTH = (307, 545)              # centre of the drawn mouth, source px
# eyes, source px: the area wiped for a blink (lash + iris, not the outer
# wing) and the lowered lash drawn in its place, from the inner corner out
EYES = [
    dict(wipe=[(150, 398), (245, 388), (252, 420), (240, 474), (168, 474), (150, 446)],
         lid=[(246, 420), (232, 434), (206, 442), (180, 440), (150, 428)]),
    dict(wipe=[(332, 394), (380, 366), (427, 360), (427, 452), (358, 452), (332, 412)],
         lid=[(334, 400), (358, 416), (388, 423), (412, 417), (432, 396)]),
]
CHEEKS = [(200, 492), (412, 480)]   # blush, source px


def main():
    art = Image.open(SRC).convert("L")
    d = ImageDraw.Draw(art)
    mx, my = MOUTH
    d.ellipse((mx - 44, my - 28, mx + 44, my + 26), fill=255)

    blank = art.copy()                             # eyes wiped: moods draw their own
    db = ImageDraw.Draw(blank)
    for e in EYES:
        db.polygon(e["wipe"], fill=255)

    shut = art.copy()
    ds = ImageDraw.Draw(shut)
    for e in EYES:
        ds.polygon(e["wipe"], fill=255)
        lid = e["lid"]                             # thick in the middle, thin at the inner corner
        for i in range(len(lid) - 1):
            ds.line(lid[i:i + 2], fill=0, width=(3, 6, 8, 9)[i], joint="curve")

    s = FACE_H / (CROP_Y1 - CROP_Y0)
    w = round(art.width * s)

    def bake(im):
        im = im.crop((0, CROP_Y0, im.width, CROP_Y1)).resize((w, FACE_H), Image.LANCZOS)
        lv = []
        for v in im.get_flattened_data():
            ink = min(1.0, (1 - v / 255) * 1.7)      # thin lines fade when shrunk: boost
            lv.append(0 if ink < .16 else 1 if ink < .42 else 2 if ink < .72 else 3)
        return lv

    open_, shut_, blank_ = bake(art), bake(shut), bake(blank)
    rows = [y for y in range(FACE_H) if open_[y * w:(y + 1) * w] != shut_[y * w:(y + 1) * w]]
    ey0, ey1 = rows[0], rows[-1] + 1

    def pack(lv):
        out = []
        for i in range(0, len(lv), 4):
            b = 0
            for k, v in enumerate(lv[i:i + 4]): b |= v << (6 - 2 * k)
            out.append(b)
        return out

    stride = (w + 3) // 4
    def rowpack(lv, y0, y1):
        out = []
        for y in range(y0, y1): out += pack(lv[y * w:(y + 1) * w] + [0] * (stride * 4 - w))
        return out

    def carr(name, data):
        lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 20]) for i in range(0, len(data), 20)]
        return f"static const uint8_t {name}[{len(data)}] PROGMEM = {{\n  " + ",\n  ".join(lines) + "\n};\n"

    sx = lambda x: (320 - w) / 2 + x * s
    sy = lambda y: (y - CROP_Y0) * s
    OUT.write_text(
        "#pragma once\n// Generated by tools/make_catgirl.py from tools/art/catgirl.png. Do not edit.\n"
        "// 2-bit ink levels (0 paper .. 3 black), 4 px per byte, MSB first.\n"
        "#include <stdint.h>\n#ifndef PROGMEM\n#define PROGMEM\n#endif\n\n"
        f"#define CAT_W {w}\n#define CAT_H {FACE_H}\n#define CAT_X {(320 - w) // 2}\n#define CAT_STRIDE {stride}\n"
        f"#define CAT_EYE_Y0 {ey0}\n#define CAT_EYE_Y1 {ey1}\n"
        + "".join(f"#define CAT_EYE{i}_X {sx(sum(p[0] for p in e['wipe']) / len(e['wipe'])):.1f}f\n"
                  f"#define CAT_EYE{i}_Y {sy(sum(p[1] for p in e['wipe']) / len(e['wipe'])):.1f}f\n"
                  for i, e in enumerate(EYES))
        + 
        f"#define CAT_MOUTH_X {sx(mx):.1f}f\n#define CAT_MOUTH_Y {sy(my):.1f}f\n#define CAT_SCALE {s:.4f}f\n"
        + "".join(f"#define CAT_CHEEK{i}_X {sx(x):.1f}f\n#define CAT_CHEEK{i}_Y {sy(y):.1f}f\n"
                  for i, (x, y) in enumerate(CHEEKS))
        + "\n" + carr("catArt", rowpack(open_, 0, FACE_H)) + "\n" + carr("catEyesShut", rowpack(shut_, ey0, ey1))
        + "\n" + carr("catEyesBlank", rowpack(blank_, ey0, ey1)))
    print(f"{OUT.name}: {w}x{FACE_H}, eye rows {ey0}-{ey1}, "
          f"{stride * FACE_H + 2 * stride * (ey1 - ey0)} bytes")

    if len(sys.argv) > 1:                          # debug: the source edits, full size
        both = Image.new("L", (art.width * 2, art.height), 255)
        both.paste(art, (0, 0)); both.paste(shut, (art.width, 0))
        both.crop((0, 300, both.width, 620)).save(sys.argv[1])


if __name__ == "__main__":
    main()
